version: '3.1'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:5.0 
    volumes: 
      - './services/mrss.api:/app'
    working_dir: '/app'
    ports: 
      - '5000:5000'
    entrypoint: "dotnet watch run --urls http://*:5000"