# TODO: Optimize image sizing

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# copy everything else and build
COPY . ./

RUN dotnet publish services/mrss.api -c Release -r linux-x64 -o out /p:PublishSingleFile=True

# build runtime image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build-env /app/out ./

COPY --from=build-env /app/services/mrss.api/VERSION ./

EXPOSE 80

ENTRYPOINT ["./mrss.api"]
